"""Positioning coach.

Drafts a board CV, a director bio and outreach messages. If Azure OpenAI
credentials are configured the drafts are generated by the model; otherwise a
deterministic template engine produces the same artefacts so the demo always
runs offline.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Optional

from .models import Candidate, FitResult, Opportunity


@dataclass(frozen=True)
class Draft:
    """A generated artefact plus the engine that produced it."""

    kind: str
    content: str
    engine: str


def azure_openai_configured() -> bool:
    """True when Azure OpenAI environment variables are present."""
    return bool(
        os.getenv("AZURE_OPENAI_ENDPOINT")
        and os.getenv("AZURE_OPENAI_API_KEY")
        and os.getenv("AZURE_OPENAI_DEPLOYMENT")
    )


def _generate(prompt: str) -> Optional[str]:
    """Call Azure OpenAI when configured; return None to fall back to templates."""
    if not azure_openai_configured():
        return None
    try:  # pragma: no cover - requires live Azure credentials
        from openai import AzureOpenAI

        client = AzureOpenAI(
            azure_endpoint=os.environ["AZURE_OPENAI_ENDPOINT"],
            api_key=os.environ["AZURE_OPENAI_API_KEY"],
            api_version=os.getenv("AZURE_OPENAI_API_VERSION", "2024-10-21"),
        )
        response = client.chat.completions.create(
            model=os.environ["AZURE_OPENAI_DEPLOYMENT"],
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a board search adviser. Write in Australian English, "
                        "in the register of a board CV: governance-first, outcome-led, "
                        "no operational detail."
                    ),
                },
                {"role": "user", "content": prompt},
            ],
            temperature=0.4,
        )
        return response.choices[0].message.content
    except Exception:  # pragma: no cover - network/credential failures
        return None


def _bullets(items: list[str], prefix: str = "- ") -> str:
    return "\n".join(f"{prefix}{item}" for item in items) if items else f"{prefix}(none recorded)"


def board_cv(candidate: Candidate, fit: Optional[FitResult] = None) -> Draft:
    """Draft a board CV — governance-first, unlike an executive resume."""
    target = fit.opportunity if fit else None
    prompt = (
        f"Draft a one-page board CV for {candidate.name} ({candidate.headline}). "
        f"Skills: {', '.join(candidate.skills)}. Credentials: {', '.join(candidate.credentials)}. "
        f"Board experience: {'; '.join(candidate.board_experience)}. "
        f"Achievements: {'; '.join(candidate.achievements)}."
        + (f" Target board: {target.title} at {target.organisation}." if target else "")
    )
    generated = _generate(prompt)
    if generated:
        return Draft("board_cv", generated, "azure-openai")

    heading = f"# {candidate.name}\n{candidate.headline}\n"
    if target:
        heading += f"\n_Prepared for: {target.title}, {target.organisation}_\n"
    content = (
        f"{heading}\n"
        "## Board value proposition\n"
        f"{candidate.years_experience} years of executive experience across "
        f"{', '.join(candidate.sectors) or 'multiple sectors'}, offering boards depth in "
        f"{', '.join(candidate.skills[:4])}.\n\n"
        "## Governance experience\n"
        f"{_bullets(candidate.board_experience)}\n\n"
        "## Governance credentials\n"
        f"{_bullets(candidate.credentials)}\n\n"
        "## Selected outcomes\n"
        f"{_bullets(candidate.achievements)}\n\n"
        "## Skills matrix contribution\n"
        f"{_bullets(sorted(candidate.skills))}\n"
    )
    if fit:
        content += (
            "\n## Alignment to this board\n"
            f"{_bullets(list(fit.rationale))}\n"
            "\n## Development priorities\n"
            f"{_bullets(list(fit.gap_actions))}\n"
        )
    return Draft("board_cv", content, "template")


def director_bio(candidate: Candidate) -> Draft:
    """Draft a short third-person director bio."""
    prompt = (
        f"Write a 90 word third-person director bio for {candidate.name}, {candidate.headline}, "
        f"with strengths in {', '.join(candidate.skills[:5])}."
    )
    generated = _generate(prompt)
    if generated:
        return Draft("director_bio", generated, "azure-openai")

    board_line = (
        f" {candidate.name.split()[0]} currently serves as "
        f"{candidate.board_experience[0]}."
        if candidate.board_experience
        else ""
    )
    content = (
        f"{candidate.name} is a non-executive director candidate with "
        f"{candidate.years_experience} years' experience across "
        f"{', '.join(candidate.sectors) or 'multiple sectors'}. "
        f"{candidate.name.split()[0]} brings board-level strength in "
        f"{', '.join(candidate.skills[:4])}, and is known for "
        f"{candidate.achievements[0].lower() if candidate.achievements else 'delivering under scrutiny'}."
        f"{board_line} "
        f"Credentials: {', '.join(candidate.credentials) or 'in progress'}."
    )
    return Draft("director_bio", content, "template")


def outreach_message(
    candidate: Candidate,
    opportunity: Opportunity,
    *,
    recipient: str = "Nominations Committee",
    intro_via: Optional[str] = None,
) -> Draft:
    """Draft an outreach email to a nominations committee or search firm."""
    prompt = (
        f"Write a concise outreach email from {candidate.name} to {recipient} about the "
        f"{opportunity.title} vacancy at {opportunity.organisation}. Strengths: "
        f"{', '.join(candidate.skills[:5])}."
        + (f" Mention the mutual connection {intro_via}." if intro_via else "")
    )
    generated = _generate(prompt)
    if generated:
        return Draft("outreach", generated, "azure-openai")

    intro_line = (
        f"{intro_via} suggested I make contact directly. "
        if intro_via
        else f"I noted the {opportunity.title} vacancy via {opportunity.source}. "
    )
    content = (
        f"Subject: {opportunity.title} — {candidate.name}\n\n"
        f"Dear {recipient},\n\n"
        f"{intro_line}"
        f"I am writing to express interest in the {opportunity.title} role at "
        f"{opportunity.organisation}.\n\n"
        f"Across {candidate.years_experience} years I have worked at the intersection of "
        f"{', '.join(candidate.skills[:3])}. "
        f"{candidate.achievements[0] if candidate.achievements else ''}\n\n"
        f"Given the board's stated need for {', '.join(opportunity.required_skills)}, I believe I "
        "can contribute from day one, and I would welcome a short conversation.\n\n"
        f"Kind regards,\n{candidate.name}\n"
    )
    return Draft("outreach", content, "template")
